apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ZQXvceZHngqxllNWo5MSQNyTY/TmrTchovyF+11zSBKMHHhLz23D5ufjTMLHaqs1KwT3Wf7ng6vEBrM9v7sxShbLOQ1J9pfhWa6zKWGayXaw4EWtkHj6Wr6ufEAzAcWu76PW9vvMmBVoUscIxctwyzIYSwHbqUTx/zNAhYYVVmxGxhSFtZfkLtorsfPZ+F2f/0J7p3GX8Ku5IAEH9VAUeiLAyn59EwVv+f3Th+1ETlOr1QPn0KAHTxr0Tg7w8MJrHOOWuLcgVH65nVCFIWL8wj62csCQk3xkb7vDk747KK821lZA8j4MyXGn2F9bqRTpi2FlyMRner9nFFAtexpOeKguhOGJUnMSPWAhenLNy60tKA+wtmsKKeLpdBTunxkv,iv:OQyJWNCEfh5bC/wB/I9VDmQrjpAXdhck8+rOimvKJjs=,tag:6/yAvHgOEfHOktWEy/JvRA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NCuwFawMZSkFFXqz6wVO/4P7LPpi3nzAkaTcNdJWyzpLRM2TUL/gw5R8EXLwdLKlimdh5cKm6X0xm2dBOTCL2bKREV2qCQNYqOTk1yBH6iSFoFQ7uTEHf68Y3DNuGidNywWyks307lQWyJw9QW+hNnFNsT9sH+j2SNxss3re753Uy9fbTMBOdw1vBUp/96+qgQUH5jv/xbJCtkKP9naJGwOPCNcSnAc/Mk6PQtP7x4Ppv5cfNf4Ogbupphqx0NMnBlcGO2Vr1TF1krLu5g==,iv:MW7hBb7z7UjYYyxan8FD/3r/xN4Sg+XSzI0N4GREepU=,tag:GqKh3qXcQMbRFw7LZpnIKQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:cuo4n6vWEt8BRlT+++adezaTsn4mldcQWOoJmJRIKdb3J0//cIbpojBhqyNEn2FpblqrcBq6KF5tyiexbj1Q+NqkOe0vDnCqaiOzd7Y1erEOahAQf2bczk8Topdj9gzNAWcg+sqs8ago2HXmvNY3BURVJ5j65DpUH86UofvUKSF5850zgVP2Dl9FgsmSc2FXj2gKGFI27dM3pUrmbFbA2R6FB4Ry3tGO5d0M,iv:vKNJCdMJxvK5r0FsKFkxbZ3eYLXTyg96Sh544jDXgUk=,tag:iwUFKbIyAejTTqsrK+0/cA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18e6ndkyv6hedmhxvrlz0m5hpq9rly6gknvlez8s7el33uah9v4asyt25ks
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWEw5UVgrYm4vT0ZESUJE
            UUJGYU9ndVhqN25UMlhpSlk1c3ZMZzRCZTBVCjRTTDMwT2t3Vm1CNzI4eWJ2anA0
            QzNSUEdVdCtVWGhLekdQb3hpRkZJUG8KLS0tIDBobE9nV240NXNsRjRyMklsTm1M
            eGZLdUg3bUJQRVFmUjB3djNZZHFlbTQKBdNECbCnlgIjFwRVdmNo1OliC13r0WTw
            CDUDXmmazx3taPJiYTalQGkVvm0Fin9RcsqJUy0wmreOZ8JZdRWXOQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T23:44:50Z"
    mac: ENC[AES256_GCM,data:dyAr73qVJNM/Er2zJOFeznRsnh58lvG2GBdvW0rJVbf9Tv9CKQfKsV0ZqqzVmGcTgxde9mAzhriUE6//KkD1QYkFUbGgF2PvwY+3FAf8MWEU1aZi4M+ovjlKCrc3volD8eji5sqr8bxHe2GGArqDCRsS+kw5d+7JsoTCPb9Qoxo=,iv:2JIFimKYiMVZx2mB11fwuQJUcjtNeA5iWBphFMii0Jg=,tag:S+WChweHnK/wlkq4X9qL2w==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
