apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Z3TZ5LWnJCTw6Ml+viQ2cfNpOBXieAXTTm6R93K4dKvtTcekpuWegpfC+3R7pBazzgCtChEmybtu4FYqu/7jwmTsUWqo2qYc/c3Ax/e7w16ivVaD1dp/EiYqa4AUvIRyT6r/7j3K9P2Bu4A+9wGWFRSn+kQbDgL/4BAXmllQTtGu6UrTabSRORb9Lv1tNjThOuqDHC7StgypH5nzpU95GkkcGaXeXAu6Xo4NhvbbBv+nH6xcNPiGIrT8Il3vV8Rs1VR2WFvGwi8xbRCABLI7AVfL/xUkN4XNxEsVwNfk/dajQyMtHwoZWs2Hb4AqAjprsXeRBKBrLLZsRMZmDWuP0mAYERZgaAcnuZT4arD83L2bSDaG9iPkoijs1pF9826/,iv:wy+EG1umThmrXi9ivcIAruPD0ooIuo6xEwo2NvbkO9I=,tag:Q1Na0PUAYOBzeanOeZ7GRA==,type:str]
    identity.pub: ENC[AES256_GCM,data:o7n3+UFAD7m+4VFICDksIRaL2BXfPPwuNpadXHjrbF0y3M/RVIirc9SAnweWeLUKsoR27rs4VNWF3gGlj8arEYqiCU8G5LrnawZ+k3TWNcReMJfmP/swQkHIrEK4x8nzs/BDltTZl64OcND7KCy5EtDrHT53rLxRMy+8k2AJC1vP36jayQUjlXSb43Z91Hr2qPPs2TyyANHo2TCAjA8cWC55/T4Nl4fiVCC+RS6G02IXheuJVVzq/XZ72mzLXkZtn0dAIHlTZLI93tfx4g==,iv:sCOCdh2/+I6+J7B0S2PQO2dx3KOFBf9Z8NIdz/MQP7s=,tag:tsJ+3X+YA1EIDDxUnxlnAw==,type:str]
    known_hosts: ENC[AES256_GCM,data:B4QCrVdeuRB7iiwv+McwlbHUyMRolOZI1wMpi+O0crtS6Diqj8EFwf9Xuqt7WC2gwYsOtuQJGP3njBgYcBijoz1sHDsXCyeEQOX0o5oYxDg5LXTRuLXJZjdS8C6eI+tXkzFgyFLrz908P5S0f5sNpdFe6ekdPGVZqQ8TRfIJ8n03Hkd5wv9KAe5MbUdSWebYzJQtqqaOcFuDKqTM00g6mxTISuw8n1n1vs8q,iv:oZexmaxT/iBIS3zAAyZnW+MbZg/iR6TQBSpczJCrMZY=,tag:pGOhSHtQmQR3zpdUGgrW/w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18e6ndkyv6hedmhxvrlz0m5hpq9rly6gknvlez8s7el33uah9v4asyt25ks
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1M09YUEt4Rmh0cVZ4M3JO
            dVpweWg3VS9kWG5PSkxjMGRTcVFpZUFLRGtFClhyWnREWEpwY2pseTYvd0g4OUlE
            K2RlL283eGZBNTJtSTVDa0l6MXRyWGMKLS0tIE5rT0c1SFpFWlM5QzFyb0xMeVJZ
            bXJ4MFhybmJxWEFpMFVLTy9rTkovOHcKaLxdxDZp3PXcIpiGkZNaptHZF+tN1CQx
            znbOBANvQcQFTaOCePXVTHld4IPJTJMxjObapSvbq5hbUmfEQFdTFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-08T21:27:33Z"
    mac: ENC[AES256_GCM,data:1kTy/aInHGnhajyQ/0BjayT3ZenchCbnPScQ5sN7wptHAKLhwdqa6vKoD+VrKv635QiiLxMWunwmZUS2Q0jYeANQAo/hdaw97VdXmdzoe9Mceo2YYOlxQpV5rxVJv7Kd2y5UBuiUmKurZUKRTF6OeeRhIdw5w0jbpXQc9fwodB4=,iv:Yr1lTaF4HLzZ/X97VQR4qGJCohaefhBxWmYCNamRlnw=,tag:f9yuMAs5uxnikWpZtqITcA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
