apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:+5LYlp0e2cJciGvVRiiv2NTS2raoziU/4Ots+DAYLbGWJjkKgOAI99e7RsNMtRdkchOtiXQ+zdseHIT+Unnx1abokWillwLYCHjthQ2KGrHj4+TBfM6fotjD5ybIY6a6JmN+WFXDJVMFfttgylVHgApUhIIge+/cqPoAOiOF4ardva5+RVmrtMqE0kovJtG+ZNtIwk9Rm27C55HLzBNOT7sW8TdNRJWPLm8TL0hJxg+6fPqdbH9fYb8JMPaoDDcy9eqsTN7PtiniHY2ASJ0sL34JbZkN06G1TSst7jsmqOGB04e+ZWCQjXbSEljpydQ9UF+uEvjXdpQRw7fAJIkl0Q4HB3KVDx4wdDTBrgR3NJgYWb2g0SjWsYGxlsdA5HiG,iv:O9Hsifab5d2Ay/UoEbpPG8isyEep4x3NEsDG6Uobf+s=,tag:3NfctvVuJyCM7mPe0TEwEA==,type:str]
    identity.pub: ENC[AES256_GCM,data:75Co/njnauFxw2knhzmPXru0cnYv0MLpFBYz4D6TR9Z9cD5fwCbY7DHqjPprky2oPEP0TN5JpuQSVd3eCgCMJACpzRiAzRdKVChLIZp7EPwOBH2ShxKpDk3jEnd+Yp3+UMs4Svkw/OY441MYOQU0Oh3iYT9c7wTqqAlWneM09jGxxL4TBt05kMCfqr+/oJyPKInvfAFgvPRikUcgYBD2oXbEH3jNit8eW6NSaVUzTncIokvVKeK32KKxqQ48tgd/byZjnbfC50zmOCQoiA==,iv:sqRQMZf+kza+IbhnfannyXHhKXId5KyQY+gWNU3L15c=,tag:52wAkNy7LrAzAZwt0gkPww==,type:str]
    known_hosts: ENC[AES256_GCM,data:r6hmB/+QXwCDCbJWLz7zzdyQ7450ijvMphWeXWYwHMN1FFaSgqWdCz0SkI3X6E/voaIcC1/9lfdRZFlj/QBONxRqkStUFCNmxVP8UCgqna+erkjSNeBosFVdLox5FvISpqlb5CI3M8oTPFJcOoAyKXgBKPa5nJCCfwyexDMJqSHd8zwsTnO5gInY1JhCd1KJXootme0HQzMk6iRRvgB/cIengkXuJ7Dey0ID,iv:f36tZ/QzR7xwqRx8D6aWpvz1mSE7kdFcEKRW8eKdyFw=,tag:XQfFJyDItJL4q7QIWYNSTg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age18e6ndkyv6hedmhxvrlz0m5hpq9rly6gknvlez8s7el33uah9v4asyt25ks
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQyt3QVhmTGZMdGhFdGJL
            WnNUZlFKRlhpOVZtY1hCSzU5K2NtYm5FVUNvCk90cjlWQzlyS3F6MGtGSkJPYzRI
            MGVBV0tzL3JKVVlQMlFUcVNSeHhROFEKLS0tIFQ0RTAxeGhJSUM4UXRFTFJQdTVr
            aUFybnRMZlord1ArL0QvanVraHBrOGsKsiF10HyM/TTSGfymne4hTS0mnyxaCGaU
            VNgVnhYv6avOmoqlompA5Tr7S+KCR0YoEWJfVWZxLOzoc/9tYaOMsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T00:17:41Z"
    mac: ENC[AES256_GCM,data:2T4v91rCRfoTygOO5I/zqQg/PIlqj5LUPV501wN/sTSQT//2TRwERjaUFYiDBOoMHOBcRrkf5+rVovPCiwB52CwPHjUPGvlAYnp6JDZsVo4hOvz0pwUvySA0xb/wCK4DTKXGWN68nsTh/paKV9rTJX9XqMk0EUhBIC2G4pkPp5g=,iv:GU7ir+r0Z9gdu/8QAnrRpiBLNa2oxxhsBUBMx04Cu3k=,tag:PLttrXM2+BGRWt6TzuIHzg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
